version: "3.9"
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=DB
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=Password1
    volumes:
      - ./app:/app
    networks:
      recipe-app-api:
    command: > 
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    networks:
      recipe-app-api:
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password1
volumes:
  postgres-db-data:
networks:
  recipe-app-api: